"""The baked-in brain.

Every entry here is a piece of knowledge that used to require a smart model to
"just know". Encoding it once makes the tool fast, offline, free, and — most
importantly — *consistent*. The LLM is only consulted for things NOT covered
here (see classify.py).

Tiers:
    safe   -> regenerates on its own; deleting it costs nothing but time
    review -> reclaimable, but you choose (a reinstall/redownload is needed)
    keep   -> never suggest deleting; real data or sandbox state

Rules are matched most-specific-first. The first match wins.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from fnmatch import fnmatch

HOME = os.path.expanduser("~")


@dataclass(frozen=True)
class Hit:
    tier: str          # "safe" | "review" | "keep"
    label: str         # human name for the thing
    why: str           # one line: why it's safe / why to keep
    source: str = "knowledge"


@dataclass(frozen=True)
class Rule:
    # match if fnmatch(full_path, path_glob) OR basename matches name_glob
    tier: str
    label: str
    why: str
    path_glob: str | None = None
    name_glob: str | None = None


def _h(p: str) -> str:
    return os.path.join(HOME, p)


# Order matters: put narrow rules before broad ones.
RULES: list[Rule] = [
    # ---- KEEP: never delete these (real data / sandbox state) ----
    Rule("keep", "Keychains", "your saved passwords and certificates",
         path_glob=_h("Library/Keychains*")),
    Rule("keep", "App sandbox data", "live app data, not a cache",
         path_glob=_h("Library/Containers/*")),
    Rule("keep", "Shared app data", "shared app state, not a cache",
         path_glob=_h("Library/Group Containers/*")),
    Rule("keep", "Photos library", "your photo library",
         name_glob="*.photoslibrary"),
    Rule("keep", "Mail data", "downloaded mail and attachments",
         path_glob=_h("Library/Mail*")),
    Rule("keep", "Messages history", "your iMessage history",
         path_glob=_h("Library/Messages*")),

    # ---- SAFE: caches that always regenerate ----
    Rule("safe", "pip download cache", "Python re-downloads on next install",
         path_glob="*/Caches/pip"),
    Rule("safe", "pip cache", "Python re-downloads on next install",
         path_glob=_h(".cache/pip")),
    Rule("safe", "Browser cache", "the browser rebuilds it automatically",
         path_glob="*/Caches/Google*"),
    Rule("safe", "Browser cache", "the browser rebuilds it automatically",
         path_glob="*/Caches/BraveSoftware*"),
    Rule("safe", "Browser cache", "the browser rebuilds it automatically",
         path_glob="*/Caches/com.operasoftware*"),
    Rule("safe", "Spotify cache", "streamed audio cache, re-fills on play",
         path_glob="*/Caches/com.spotify*"),
    Rule("safe", "Playwright browsers", "re-downloaded by `playwright install`",
         path_glob="*/Caches/ms-playwright"),
    Rule("safe", "Electron updater leftovers", "old app-update staging",
         name_glob="*.ShipIt"),
    Rule("safe", "Homebrew downloads", "re-downloaded on next `brew` install",
         path_glob="*/Caches/Homebrew*"),
    Rule("safe", "npm cache", "npm re-downloads on next install",
         path_glob="*/.npm/_cacache"),
    Rule("safe", "Yarn cache", "yarn re-downloads on next install",
         path_glob="*/Caches/Yarn*"),
    Rule("safe", "Gradle cache", "re-downloaded on next build",
         path_glob="*/.gradle/caches"),
    Rule("safe", "Xcode DerivedData", "Xcode rebuilds it on next build",
         path_glob="*/Developer/Xcode/DerivedData*"),
    Rule("safe", "Simulator caches", "regenerated by the simulator",
         path_glob="*/Developer/CoreSimulator/Caches*"),
    Rule("safe", "conda package cache", "conda re-downloads packages",
         path_glob="*/pkgs"),
    Rule("safe", "Python bytecode", "regenerated automatically",
         name_glob="__pycache__"),
    Rule("safe", "pytest cache", "regenerated on next test run",
         name_glob=".pytest_cache"),
    Rule("safe", "mypy cache", "regenerated on next type-check",
         name_glob=".mypy_cache"),
    Rule("safe", "ruff cache", "regenerated on next lint",
         name_glob=".ruff_cache"),
    Rule("safe", "Turd cache", "regenerated build cache",
         name_glob=".turbo"),
    Rule("safe", "Arduino installers", "downloaded installers, re-fetched",
         path_glob=_h("Library/Arduino15/staging")),
    Rule("safe", "Trash", "already-deleted files taking space",
         path_glob=_h(".Trash")),

    # ---- SAFE: caches buried inside app folders (found by drilling) ----
    Rule("safe", "GPU shader cache", "regenerated by the app",
         name_glob="GPUCache"),
    Rule("safe", "Shader cache", "regenerated by the app",
         name_glob="ShaderCache"),
    Rule("safe", "Shader cache", "regenerated by the app",
         name_glob="GrShaderCache"),
    Rule("safe", "Code cache", "regenerated by the app",
         name_glob="Code Cache"),
    Rule("safe", "Crash reports", "old crash dumps",
         name_glob="Crashpad"),
    Rule("safe", "Extension cache", "re-fetched by the browser",
         name_glob="Component Crx Cache"),
    Rule("safe", "Extension cache", "re-fetched by the browser",
         name_glob="component_crx_cache"),

    # ---- REVIEW: reclaimable but needs a reinstall/redownload ----
    Rule("review", "Node modules", "regenerates with `npm install`",
         name_glob="node_modules"),
    Rule("review", "Python virtualenv", "recreate with a fresh venv + install",
         name_glob=".venv"),
    Rule("review", "Python virtualenv", "recreate with a fresh venv + install",
         name_glob="venv"),
    Rule("review", "Build output", "regenerates on next build",
         name_glob="dist"),
    Rule("review", "Build output", "regenerates on next build",
         name_glob="build"),
    Rule("review", "Next.js build", "regenerates on next build",
         name_glob=".next"),
    Rule("review", "Rust/Java target dir", "regenerates on next build",
         name_glob="target"),
    Rule("review", "Maven repository", "re-downloaded on next build",
         path_glob="*/.m2/repository"),
    Rule("review", "Arduino board cores", "re-add via Boards Manager",
         path_glob=_h("Library/Arduino15/packages")),
    Rule("review", "Claude sandbox images", "Claude re-downloads when needed",
         path_glob="*/Application Support/Claude/vm_bundles"),
    Rule("review", "Browser offline cache", "clears offline site data; regenerates",
         name_glob="Service Worker"),
    Rule("review", "App cache", "generally safe; may re-download some data",
         name_glob="Cache"),
    Rule("review", "App cache", "generally safe; may re-download some data",
         name_glob="Cache_Data"),
    Rule("review", "App cache", "generally safe; may re-download some data",
         name_glob="CachedData"),
    Rule("review", "Dynamic wallpapers", "re-downloaded if you pick them again",
         path_glob="*/Application Support/com.apple.wallpaper*"),
    Rule("review", "Docker disk image", "large VM disk; resets Docker data",
         name_glob="Docker.raw"),
    Rule("review", "Steam game data", "re-downloadable game files",
         path_glob="*/Application Support/Steam/steamapps*"),

    # ---- REVIEW: local model stores (large, but re-downloadable) ----
    Rule("safe", "HuggingFace cache", "re-downloads models/datasets on demand",
         path_glob="*/.cache/huggingface*"),
    Rule("safe", "PyTorch hub cache", "re-downloads models on demand",
         path_glob="*/.cache/torch*"),
    Rule("review", "LM Studio models", "re-downloadable from LM Studio",
         path_glob="*/.lmstudio/models*"),
    Rule("review", "LM Studio models", "re-downloadable from LM Studio",
         path_glob="*/.lmstudio*"),
    Rule("review", "Ollama models", "re-pullable with `ollama pull`",
         path_glob="*/.ollama/models*"),
    Rule("review", "Keras models", "re-downloadable model cache",
         path_glob="*/.keras*"),

    # ---- broad fallbacks (kept last) ----
    Rule("review", "App cache", "app-specific cache; usually safe to clear",
         path_glob="*/Library/Caches/*"),
    Rule("review", "Log files", "old logs; app keeps writing new ones",
         path_glob="*/Library/Logs/*"),
]


def look_up(path: str) -> Hit | None:
    """Return knowledge about a path, or None if we don't recognise it."""
    base = os.path.basename(path.rstrip("/"))
    for r in RULES:
        if r.path_glob and fnmatch(path, r.path_glob):
            return Hit(r.tier, r.label, r.why)
        if r.name_glob and fnmatch(base, r.name_glob):
            return Hit(r.tier, r.label, r.why)
    return None


# Large loose files aren't caches — they're YOUR data. We classify them by
# extension only to give a helpful label; the tier is always "review" and the
# reason makes clear the tool can't know if you still need it.
_EXT_KINDS = {
    "ML model": {".h5", ".hdf5", ".pt", ".pth", ".ckpt", ".safetensors",
                 ".pb", ".onnx", ".tflite", ".pkl", ".joblib", ".gguf", ".ggml"},
    "dataset": {".csv", ".tsv", ".parquet", ".jsonl", ".arrow",
                ".npy", ".npz", ".mat", ".feather"},
    "media file": {".mp4", ".mov", ".avi", ".mkv", ".wav", ".flac", ".psd"},
    "archive": {".zip", ".tar", ".gz", ".tgz", ".bz2", ".xz", ".rar",
                ".7z", ".dmg", ".iso", ".pkg"},
}


def file_kind(path: str) -> Hit:
    """Label a large loose file by extension. Always 'review' — it's user data."""
    ext = os.path.splitext(path)[1].lower()
    for label, exts in _EXT_KINDS.items():
        if ext in exts:
            return Hit("review", f"Large {label}",
                       "your file — delete only if you can recreate it", "extension")
    return Hit("review", "Large file",
               "your file — delete only if you can recreate it", "extension")

